name: Backend CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: memoryvault
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports: ['5432:5432']


    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://user:pass@localhost:5432/memoryvault
      HF_API_KEY: ${{ secrets.HF_API_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      FRONTEND_URL: http://localhost:5173

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install backend dependencies
      run: npm ci
      working-directory: ./MemoryVault-server

    - name: Generate Prisma Client
      run: npx prisma generate
      working-directory: ./MemoryVault-server

    - name: Apply Prisma Migrations
      run: npx prisma migrate deploy
      working-directory: ./MemoryVault-server

    - name: Run Backend Tests
      run: npm test
      working-directory: ./MemoryVault-server